baseURL = "https://nikhil-vemula.github.io/"
languageCode = "en-us"
title = "Nikhil Vemula"
theme = "hugo-minimal-blog-theme"
pygmentsUseClasses=true
paginate = 5

[author]
  name = "Nikhil Vemula"
  title = "Application Developer"
  subtitle = "Coder by :heart:"


[[params.social]]
  name = "github"
  icon = "fab fa-github-square"
  url = "https://github.com/nikhil-vemula"

[[params.social]]
  name = "linkedin"
  icon = "fab fa-linkedin"
  url = "https://www.linkedin.com/in/srinivasanikhil/"

[[params.social]]
  name = "twitter"
  icon = "fab fa-twitter-square"
  url = "https://twitter.com/srinivasanikhil"

[[params.social]]
  name = "facebook"
  icon = "fab fa-facebook-square"
  url = "https://www.facebook.com/nikhilvemula97"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2